### PR TITLE
add a prompt window to input a message for  push if user select push button

### PR DESCRIPTION
**Pull request by xpix**

### CODE REVIEW

**Comment by chilipeppr** [comment]
When you reload the runme.js homepage, does that no longer re-generate and
then push to Github? Do you always have to then click "Push to Github"?

**Comment by xpix** [comment]
Hi John,

The reload of the page has the Same effect as before. This will push all changes with the normal default message. Only if you select the button, the prompt will open and you can add a message, if empty then the default message will use.

Or you found a bug :)

Frank

Von meinem iPad gesendet

**Comment by chilipeppr** [comment]
I fixed a bug where you were not actually passing to the command line

**Comment by xpix** [comment]
Ok, found it:

https://github.com/chilipeppr/widget-template/commit/1fdd7a16f86dc6c71b225f6fafcd6dab2d8ceecb

Found it. Thank you John.

_--_
_Frank Herrmann    | Software Entwicklung_
+49 172 600 40 61 | xpixer@gmail.com
Neudorfer Weg.10  | 68753 Waghäusel

2016-02-18 3:24 GMT+01:00 John Lauer notifications@github.com:

**Pull request merged**
